[package]
name = "cargo-aex"
version = "0.1.0"
edition = "2024"
authors = ["potistudio <potistudio@proton.me>"]
license = "MIT"
publish = false

[profile.release]
codegen-units = 1
lto = true

[dependencies]
anyhow = "1.0.104"
cargo_metadata = "0.23.1"
clap = { version = "4", features = ["derive"] }
plist = "1.10.1"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
tempfile = "3.27.0"
